name: Deploy AICodeSerach infra with Bicep

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'infra/azurebatch_config.bicep'
      - '.github/workflows/Deploy_AICodeSerach_Infra.yml'

permissions:
  contents: read  # No need for id-token permission

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Upload requirements.txt to Blob container
      run: |
        az storage blob upload \
            --account-name batchprereqstore \
            --container-name store \
            --name requirements.txt \
            --file dependencies/requirements.txt \
            --overwrite true \
            --auth-mode login

    - name: Deploy Azure Batch Bicep Template
      run: |
        az deployment group create \
          --resource-group AICodeSearch_RG \
          --template-file infra/azurebatch_config.bicep \
          --parameters @infra/parameters.json \
          --debug

    - name: Deploy Azure Data factory Infra Bicep Template
      run: |
        az deployment group create \
          --resource-group AICodeSearch_RG \
          --template-file infra/adf-config.bicep \
          --parameters dataFactoryName=AICodeSearch_ADF

    - name: Logout
      run: az logout
