name: Deploy Azure Batch with Bicep

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'infra/azurebatch_config.bicep'
      - '.github/workflows/Deploy_AzureBatch.yml'

permissions:
  contents: read  # No need for id-token permission

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group AICodeSearch_RG \
          --template-file infra/azurebatch_config.bicep

    - name: Logout
      run: az logout
